theme: jekyll-theme-primer
title: University Projects
description: Completed uni .git projects
url: "https://university-project-repos.github.io/.github/"
org_url: "https://github.com/University-Project-Repos"
author:
    name: Adam Ross
    url: https://r055a.github.io/R055A/
plugins:
  - jekyll-seo-tag
keywords:
  - "Mining of Social Data - 1DL465"
  - "Concurrent Algorithms and Data Structures - 1DL590"
  - "Accelerating Systems with Programmable Logic Components - 1DT109"
  - "Programming Embedded Systems, Project - 1DT108"
  - "Human-Robot Interaction with Research Project - 1MD044"
  - "Compiler Design I - 1DL321"
  - "Optimisation - 1TD184"
  - "Real Time Systems - 1DT004"
  - "Modelling for Combinatorial Optimisation - 1DL451"
  - "Computing Education Research - 1DT061"
  - "Functional Programming I - 1DL330"
  - "Project in Data Science - 1DL507"
  - "Accelerator-Based Programming - 1TD054"
  - "Digital Imaging Systems - 1MD041"
  - "Open Course on Topics in Computer Science - 1DL705 (Quantum Programming)"
  - "Cryptology - 1DT075"
  - "Information Technology and Energy Storage - 1DT115"
  - "Foundations of Data Science - 1MS048"
  - "Advanced Functional Programming - 1DL450"
  - "Advanced Probabilistic Machine Learning - 1RT003"
  - "Large Language Models and Societal Consequences of Artificial Intelligence - 1RT730"
  - "Security and Privacy - 1DT098"
  - "Information Technology and Energy Storage - 1DT107"
  - "Software Engineering Project - 1DL650"
  - "IT Systems and Human Factors - 1MD017"
  - "IT, Sustainability and Social Responsibility - 1DL008"
  - "Model-Based Design of Embedded Software - 1DT059"
  - "Parallel and Distributed Programming - 1TD070"
  - "IT, Ethics and Organisation - 1MD004"
  - "Algorithms and Data Structures III - 1DL481"
  - "Programming Embedded Systems - 1DT106"
  - "Intelligent Interactive Systems - 1MD039"
  - "Reinforcement Learning - 1RT747"
  - "Applied Linear Algebra for Data Science - 1TD060"
  - "Data Mining II - 1DL460"
  - "Deep Learning for Image Analysis - 1MD120"
  - "Data Engineering II - 1TD075"
  - "Data, Ethics and Law - 1DL002"
  - "Computer-Assisted Image Analysis II - 1TD398"
  - "Wireless Communication and Networked Embedded Systems - 1DT103"
  - "User Interface Programming II - 1MD003"
  - "Statistical Machine Learning - 1RT700"
  - "Natural Computation Methods for Machine Learning - 1DL073"
  - "Advanced Computer Architecture - 1DT024"
  - "Data Engineering I - 1TD169"
  - "User Interface Programming I - 1MD002"
  - "Secure Computer Systems I - 1DT072"
  - "Computer-Assisted Image Analysis I - 1TD396"
  - "Data Mining I - 1DL360"
  - "Maintenance Programming - 1DL601"
  - "Operating Systems I - 1DT044"
  - "Low-Level Parallel Programming - 1DL550"
  - "Platform-Spanning Systems - 1DL620"
  - "Advanced Interaction Design - 1MD001"
  - "Advanced Software Design - 1DL242"
  - "Database Design II - 1DL400"
  - "Software Testing - 1DL610"
  - "Global Software Product Development - 1DT092"
  - "Complex IT Systems in Large Organisations - 1DL630"
  - "Requirements in Agile Development - 1MD200"
  - "Software Engineering and Project Management - 1DL251"
  - "COSC121 Introduction to Computer Programming"
  - "COSC122 Introduction to Computer Science"
  - "MATH120 Discrete Mathematics"
  - "COSC261 Formal Languages and Compilers"
  - "COSC262 Algorithms"
  - "COSC264 Introduction to Computer Networks and the Internet"
  - "COSC363 Computer Graphics"
  - "COSC362 Introduction to Cybersecurity"
  - "COSC366 Research Project (UE drone simulation)"
  - "COSC367 Artificial Intelligence"
  - "COSC368 Human-Computer Interaction"
  - "COSC364 Internet Technology and Engineering (now COSC364 Internet Protocols)"
  - "SENG365 Web Computing Architectures"
  - "SENG302 Software Engineering Team Project"
  - "SENG201 Software Engineering I"
  - "SENG301 Software Engineering II"
  - "SENG199 Software Engineering Workshop Training Course"
  - "CO2012 Software Project Management and Professionalism"
  - "EDAF75 Database Technology"
  - "GEOG205 Introduction to Geographic Information Systems"
  - "GEOG313 Remote Sensing Data for Geographic Analysis"
  - "GEOG323 Geospatial Analysis in the Social and Environmental Sciences"
  - "GEOG324 Advanced GIS"
  - "Machine learning for statistical NLP: advanced - LT2926"
  - "Explainable AI - DT8060"
  - "Geospatial Analysis with Cloud Computing in Environmental Monitoring - GMA6H1"
  - "Algorithms and Systems for Autonomous Vehicles - 5EL272"
  - "SOFTENG 701 Advanced Software Engineering Development Methods"
  - "SOFTENG 754 Advanced Software Requirements Engineering"
  - "SOFTENG 750 Software Development Methodologies"
  - "COMPSYS 726 Robotics and Intelligent Systems"
