theme: jekyll-theme-primer
title: University Projects
description: Completed uni .git projects
url: "https://university-project-repos.github.io/.github/"
org_url: "https://github.com/University-Project-Repos"
author:
    name: Adam Ross
    url: https://r055a.github.io/R055A/
plugins:
  - jekyll-seo-tag
keywords:
  - "Mining of Social Data - 1DL465"
  - "Utvinning av sociala data - 1DL465"
  - "Concurrent Algorithms and Data Structures - 1DL590"
  - "Parallella algoritmer och datastrukturer - 1DL590"
  - "Accelerating Systems with Programmable Logic Components - 1DT109"
  - "Accelerering av system med programmerbara logikenheter - 1DT109"
  - "Programming Embedded Systems, Project - 1DT108"
  - "Programmering av inbyggda system, projekt - 1DT108"
  - "Human-Robot Interaction with Research Project - 1MD044"
  - "Människa-robotinteraktion med forskningsprojekt - 1MD044"
  - "Compiler Design I - 1DL321"
  - "Kompilatorteknik I - 1DL321"
  - "Optimisation - 1TD184"
  - "Optimeringsmetoder - 1TD184"
  - "Real Time Systems - 1DT004"
  - "Realtidssystem - 1DT004"
  - "Modelling for Combinatorial Optimisation - 1DL451"
  - "Modellering för kombinatorisk optimering - 1DL541"
  - "Computing Education Research - 1DT061"
  - "Datavetenskapens didaktik - 1DT061"
  - "Functional Programming I - 1DL330"
  - "Funktionell programmering I - 1DL330"
  - "Project in Data Science - 1DL507"
  - "Projekt i dataanalys - 1DL507"
  - "Accelerator-Based Programming - 1TD054"
  - "Acceleratorbaserad programmering - 1TD054"
  - "Digital Imaging Systems - 1MD041"
  - "Digitala bildalstrande system - 1MD041"
  - "Open Course on Topics in Computer Science - 1DL705 (Quantum Programming)"
  - "Öppen fördjupningskurs i datavetenskap - 1DL075 (Kvantberäkningsteknik)"
  - "Cryptology - 1DT075"
  - "Kryptologi - 1DT075"
  - "Information Technology and Energy Storage - 1DT115"
  - "Informationsteknik och energilagring - 1DT115"
  - "Foundations of Data Science - 1MS048"
  - "Dataanalysens grundvalar - 1MS048"
  - "Advanced Functional Programming - 1DL450"
  - "Avancerad funktionell programmering - 1DL450"
  - "Advanced Probabilistic Machine Learning - 1RT003 (now Advanced Probabilistic Machine Learning - 1RT705)"
  - "Avancerad probabilistisk maskininlärning - 1RT003 (nu Avancerad probabilistisk maskininlärning - 1RT705)"
  - "Large Language Models and Societal Consequences of Artificial Intelligence - 1RT730"
  - "Stora språkmodeller och sociala konsekvenser av artificiell intelligens - 1RT730"
  - "Security and Privacy - 1DT098 (now Data Security and Privacy - 1DT114)"
  - "Säkerhet och integritet - 1DT098 (nu Datasäkerhet och integritet - 1DT114)
  - "Software Engineering Project - 1DL650"
  - "Projekt i mjukvaruutveckling - 1DL650"
  - "IT Systems and Human Factors - 1MD017"
  - "IT-system och människor i samspel - 1MD017"
  - "IT, Sustainability and Social Responsibility - 1DL008"
  - "IT, hållbarhet och socialt ansvar - 1DL088"
  - "Model-Based Design of Embedded Software - 1DT059"
  - "Modellbaserad utveckling av inbyggd programvara - 1DT059"
  - "Parallel and Distributed Programming - 1TD070"
  - "Parallell och distribuerad programmering - 1TD070"
  - "IT, Ethics and Organisation - 1MD004"
  - "IT, etik och organisation - 1MD004"
  - "Algorithms and Data Structures III - 1DL481"
  - "Algoritmer och datastrukturer III - 1DL481"
  - "Programming Embedded Systems - 1DT106"
  - "Programmering av inbyggda system - 1TD106"
  - "Intelligent Interactive Systems - 1MD039 (now Intelligent Interactive Systems - 1MD032)"
  - "Intelligenta interaktiva system - 1MD039 (nu Intelligenta interaktiva system - 1MD032)"
  - "Reinforcement Learning - 1RT747 (now Reinforcement Learning - 1RT745)"
  - "Förstärkningsinlärning - 1RT747 (nu Förstärkningsinlärning - 1RT745)"
  - "Applied Linear Algebra for Data Science - 1TD060 (now Scientific Computing for Data Analysis - 1TD352)"
  - "Tillämpad linjär algebra för dataanalys - 1TD060 (nu Beräkningsvetenskap för dataanalys - 1TD352)
  - "Data Mining II - 1DL460"
  - "Informationsutvinning II - 1DL460"
  - "Deep Learning for Image Analysis - 1MD120 (now Advanced Deep Learning for Image Processing - 1MD042)"
  - "Djup maskininlärning för bildanalys - 1MD120 (nu Avancerad djupinlärning för bildbehandling - 1MD042)"
  - "Data Engineering II - 1TD075 (now Data Engineering II - 1TD076)"
  - "Data, Ethics and Law - 1DL002"
  - "Data, etik och rätt - 1DL002"
  - "Computer-Assisted Image Analysis II - 1TD398"
  - "Datoriserad bildanalys II - 1TD398"
  - "Wireless Communication and Networked Embedded Systems - 1DT103 (now Wireless Communication and Networked Embedded Systems - 1DT194 and Wireless Communication and Networked Embedded Systems, Project - 1DT195)"
  - "Trådlös kommunikation och nätverksbaserade inbyggda system - 1DT103 (nu Trådlös kommunikation och nätverksbaserade inbyggda system - 1DT194 and Trådlös kommunikation och nätverksbaserade inbyggda system, projekt - 1DT195)
  - "User Interface Programming II - 1MD003 (now User Interfaces: Programming and Evaluation - 1MD046)"
  - "Gränssnittsprogrammering II - 1MD003 (nu Användargränssnitt: programmering och utvärdering - 1MD046)"
  - "Statistical Machine Learning - 1RT700"
  - "Statistisk maskininlärning - 1RT700"
  - "Natural Computation Methods for Machine Learning - 1DL073"
  - "Naturliga beräkningsmetoder för maskininlärning - 1DL073"
  - "Advanced Computer Architecture - 1DT024"
  - "Avancerad datorarkitektur - 1DT024"
  - "Data Engineering I - 1TD169"
  - "User Interface Programming I - 1MD002 (now User Interfaces: Programming and Evaluation - 1MD046)"
  - "Gränssnittsprogrammering I - 1MD002 (nu Användargränssnitt: programmering och utvärdering - 1MD046)"
  - "Secure Computer Systems I - 1DT072"
  - "Säkra datorsystem I - 1DT072"
  - "Computer-Assisted Image Analysis I - 1TD396"
  - "Datoriserad bildanalys I - 1TD396"
  - "Data Mining I - 1DL360"
  - "Informationsutvinning I - 1DL360"
  - "Maintenance Programming - 1DL601"
  - "Underhållsprogrammering - 1DL601"
  - "Operating Systems I - 1DT044"
  - "Operativsystem I - 1DT044"
  - "Low-Level Parallel Programming - 1DL550"
  - "Lågnivå-parallellprogrammering - 1DL550"
  - "Platform-Spanning Systems - 1DL620"
  - "Plattformsöverskridande system - 1DL620"
  - "Advanced Interaction Design - 1MD001"
  - "Avancerad interaktionsdesign - 1MD001"
  - "Advanced Software Design - 1DL242"
  - "Avancerad mjukvarudesign - 1DL242"
  - "Database Design II - 1DL400"
  - "Databasteknik II - 1DL400"
  - "Software Testing - 1DL610"
  - "Mjukvarutestning - 1DL610"
  - "Global Software Product Development - 1DT092"
  - "Internationell mjukvaruutveckling, projekt - 1DT092"
  - "Complex IT Systems in Large Organisations - 1DL630"
  - "Komplexa IT-system i stora organisationer - 1DL630"
  - "Requirements in Agile Development - 1MD200"
  - "Krav inom agil utveckling - 1MD200"
  - "Software Engineering and Project Management - 1DL251"
  - "Metoder och projektledning för mjukvaruutveckling - 1DL251"
  - "COSC121 Introduction to Computer Programming"
  - "COSC122 Introduction to Computer Science"
  - "COSC261 Formal Languages and Compilers"
  - "COSC262 Algorithms"
  - "COSC264 Introduction to Computer Networks and the Internet"
  - "COSC363 Computer Graphics"
  - "COSC362 Introduction to Cybersecurity"
  - "COSC366 Research Project (UE drone simulation)"
  - "COSC367 Artificial Intelligence"
  - "COSC368 Human-Computer Interaction"
  - "COSC364 Internet Technology and Engineering (now COSC364 Internet Protocols)"
  - "SENG365 Web Computing Architectures"
  - "SENG302 Software Engineering Team Project"
  - "SENG201 Software Engineering I (now SENG201 Software Engineering Foundations)"
  - "SENG301 Software Engineering II (now SENG301 Software Engineering Methods)"
  - "SENG199 Software Engineering Workshop Training Course"
  - "CO2012 Software Project Management and Professionalism (credited at SENG202 Software Engineering Project Workshop)"
  - "EDAF75 Database Technology (credited at COSC265 Relational Database Systems)"
  - "GEOG205 Introduction to Geographic Information Systems"
  - "GEOG313 Remote Sensing Data for Geographic Analysis (now GEOG208 Remote sensing for geospatial analysis)"
  - "GEOG323 Geospatial Analysis in the Social and Environmental Sciences"
  - "GEOG324 Advanced GIS"
  - "MATH120 Discrete Mathematics"
  - "EMTH118 Engineering Mathematics 1A"
  - "EMTH119 Engineering Mathematics 1B"
  - "EMTH211 Engineering Linear Algebra and Statistics"
  - "MATH220 Discrete Mathematics and Cryptography"
  - "STAT101 Statistics 1"
  - "161250 Data Analysis"
  - "Machine learning for statistical NLP: advanced - LT2926"
  - "Explainable AI - DT8060"
  - "Geospatial Analysis with Cloud Computing in Environmental Monitoring - GMA6H1"
  - "Algorithms and Systems for Autonomous Vehicles - 5EL272"
  - "SOFTENG 701 Advanced Software Engineering Development Methods"
  - "SOFTENG 754 Advanced Software Requirements Engineering"
  - "SOFTENG 750 Software Development Methodologies"
  - "COMPSYS 726 Robotics and Intelligent Systems"
